- name: Login en ACR
  containers.podman.podman_login:
    registry: acrpractico2demo.azurecr.io
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"

- name: Subir imagen webapp
  containers.podman.podman_image:
    name: acrpractico2demo.azurecr.io/webapp
    tag: casopractico2
    path: ../imagenes/webapp
    push: true

- name: Subir imagen webapp-persistente
  containers.podman.podman_image:
    name: acrpractico2demo.azurecr.io/webapp-persistente
    tag: casopractico2
    path: ../imagenes/webapp-persistente
    push: true
