- name: Instalar dependencias previas
  apt:
    name:
      - software-properties-common
      - uidmap
    state: present
    update_cache: true

- name: Añadir clave GPG del repositorio de Podman
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key
    state: present

- name: Añadir repositorio de Podman
  ansible.builtin.apt_repository:
    repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /
    state: present

- name: Actualizar apt
  ansible.builtin.apt:
    update_cache: yes

- name: Instalar Podman
  apt:
    name: podman
    state: present

- name: Login en ACR
  containers.podman.podman_login:
    registry: acrpractico2demo.azurecr.io
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"

- name: Descargar imagen de la app
  containers.podman.podman_image:
    name: acrpractico2demo.azurecr.io/webapp:casopractico2

- name: Lanzar contenedor
  containers.podman.podman_container:
    name: webapp
    image: acrpractico2demo.azurecr.io/webapp:casopractico2
    state: started
    ports:
      - "443:443"
    restart_policy: always

- name: Generar unidad systemd para el contenedor
  command:
    cmd: podman generate systemd --name webapp --files --restart-policy always
    chdir: /root
    creates: /root/container-webapp.service

- name: Mover unidad systemd a /etc/systemd/system
  copy:
    src: /root/container-webapp.service
    dest: /etc/systemd/system/container-webapp.service
    remote_src: yes

- name: Recargar systemd
  systemd:
    daemon_reload: yes

- name: Habilitar y arrancar el contenedor como servicio
  systemd:
    name: container-webapp.service
    enabled: yes
    state: started
