- name: Instalar dependencias previas
  apt:
    name:
      - software-properties-common
      - uidmap
    state: present
    update_cache: true

- name: Añadir repositorio de Podman
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /"
    filename: "devel_kubic_libcontainers_stable"
    state: present

- name: Añadir clave GPG para libcontainers
  get_url:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key"
    dest: "/etc/apt/trusted.gpg.d/libcontainers.gpg"
    mode: '0644'

- name: Actualizar caché APT
  apt:
    update_cache: yes

- name: Instalar Podman
  apt:
    name: podman
    state: present

- name: Login en ACR
  containers.podman.podman_login:
    registry: acrpractico2demo.azurecr.io
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"

- name: Descargar imagen de la app
  containers.podman.podman_image:
    name: acrpractico2demo.azurecr.io/webapp:casopractico2

- name: Lanzar contenedor
  containers.podman.podman_container:
    name: webapp
    image: acrpractico2demo.azurecr.io/webapp:casopractico2
    state: started
    ports:
      - "443:443"
    restart_policy: always
