apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-persistente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      initContainers:
      - name: init-content
        image: busybox
        command: ["sh", "-c"]
        args: ["mkdir -p /mnt/data && chown -R 33:33 /mnt/data && chmod -R 755 /mnt/data"]
        volumeMounts:
        - name: app-volume
          mountPath: /mnt/data
      containers:
      - name: webapp
        image: acrpractico2demo.azurecr.io/webapp-persistente:casopractico2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-volume
          mountPath: /var/www/html/data
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: webapp-pvc
      imagePullSecrets:
      - name: acr-secret
