# Service de tipo LoadBalancer para exponer la aplicación web públicamente

apiVersion: v1
kind: Service
metadata:
  name: webapp-service  # Nombre del servicio
spec:
  type: LoadBalancer  # Expone el servicio con una IP pública, aunque hay otras opciones se pide que sea así
  selector:
    app: webapp  # Selecciona los pods con la etiqueta 'app: webapp'
  ports:
    - port: 80        # Puerto expuesto por el servicio
      targetPort: 80  # Puerto al que redirige en el
